# Generated by Django 6.1.1 on 2026-10-07 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-fecha_apertura']},
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'Proceso'), ('TERMINADA', 'Terminada')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_apertura',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_cierre',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['evaluador', 'estado'], name='idx_eval_evaluador_estado'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['evaluado', 'estado'], name='idx_eval_evaluado_estado'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estado'], name='idx_eval_estado'),
        ),
        migrations.AddIndex(
            model_name='periodo',
            index=models.Index(fields=['fecha_apertura', 'fecha_cierre'], name='idx_periodo_fechas'),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('evaluador', 'evaluado', 'periodo', 'cuestionario'), name='unique_evaluacion_evaluador_evaluado_periodo_cuestionario'),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.CheckConstraint(condition=models.Q(('evaluador', models.F('evaluado')), _negated=True), name='check_evaluador_diferente_evaluado'),
        ),
    ]
